apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: packersmovers
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: packersmovers
    tier: backend
  ports:
    - name: http
      protocol: TCP
      port: 8081
      # targetPort: 8081
